create table ROLES
(
    ID   BIGINT auto_increment
        primary key,
    NAME VARCHAR(255) not null
);

create table USER
(
    ID            BIGINT auto_increment
        primary key,
    E_MAIL        VARCHAR(255) not null,
    USER_PASSWORD VARCHAR(255) not null,
    PHONE_NUMBER  VARCHAR(255),
    USER_NAME     VARCHAR(255) not null
);

create table USER_ROLES
(
    USER_ID  BIGINT not null,
    ROLES_ID BIGINT not null,
    primary key (USER_ID, ROLES_ID),
        foreign key (ROLES_ID) references ROLES (ID),
        foreign key (USER_ID) references USER (ID)
);

create table BASE
(
    ID               SMALLINT auto_increment
        primary key,
    NAME             VARCHAR(255) not null,
    PRICE_MULTIPLIER DOUBLE       not null
);

create table BASKET
(
    ID        BIGINT auto_increment
        primary key,
    IS_ACTIVE BOOLEAN   not null,
    TIME      TIMESTAMP not null,
    USER_ID   BIGINT    not null,
        foreign key (USER_ID) references USER (ID)
);

create table CATEGORY
(
    ID             SMALLINT auto_increment
        primary key,
    NAME           VARCHAR(255) not null,
    CATEGORY_PRICE DOUBLE       not null
);

create table INGREDIENT
(
    ID              SMALLINT auto_increment
        primary key,
    INGREDIENT_TYPE VARCHAR(255) not null,
    NAME            VARCHAR(255) not null,
    PRICE           DOUBLE       not null
);

create table PRODUCT
(
    ID          BIGINT auto_increment
        primary key,
    DESCRIPTION VARCHAR(255),
    NAME        VARCHAR(255) not null,
    PRICE       DOUBLE,
    BASE_ID     SMALLINT     not null,
    CATEGORY_ID SMALLINT,
    foreign key (CATEGORY_ID) references CATEGORY (ID),
    foreign key (BASE_ID) references BASE (ID)
);

create table PRODUCT_INGREDIENT
(
    PRODUCT_ID    BIGINT   not null,
    INGREDIENT_ID SMALLINT not null,
    foreign key (PRODUCT_ID) references PRODUCT (ID),
    foreign key (INGREDIENT_ID) references INGREDIENT (ID)
);

create table BASKET_ITEM
(
    ID          BIGINT auto_increment
        primary key,
    DESCRIPTION VARCHAR(255),
    PRICE       DOUBLE not null,
    BASKET_ID   BIGINT not null,
    PRODUCT_ID  BIGINT not null,
        foreign key (BASKET_ID) references BASKET (ID),
        foreign key (PRODUCT_ID) references PRODUCT (ID)
);

create table ORDERS
(
    ID              BIGINT auto_increment
        primary key,
    COMMENT         VARCHAR(255),
    PHONE_NUMBER    VARCHAR(255) not null,
    PRICE           DOUBLE,
    STATUS          VARCHAR(255) not null,
    TIME            TIMESTAMP    not null,
    TYPE_OF_PAYMENT VARCHAR(255),
    USER_ID         BIGINT       not null,
        foreign key (USER_ID) references USER (ID)
);

create table ORDER_ITEM
(
    ID          BIGINT auto_increment
        primary key,
    DESCRIPTION VARCHAR(255),
    PRICE       DOUBLE,
    ORDER_ID    BIGINT not null,
    PRODUCT_ID  BIGINT not null,
        foreign key (PRODUCT_ID) references PRODUCT (ID),
        foreign key (ORDER_ID) references ORDERS (ID)
);
//#########################################################################################
//                                ROLES
//#########################################################################################

INSERT INTO PUBLIC.ROLES (NAME) VALUES ('ROLE_USER');
INSERT INTO PUBLIC.ROLES (NAME) VALUES ('ROLE_ADMIN');

//#########################################################################################
//                                  USER
//#########################################################################################

INSERT INTO PUBLIC.USER (E_MAIL, USER_PASSWORD, PHONE_NUMBER, USER_NAME) VALUES ('-', '-', null, 'Удаленный');
INSERT INTO PUBLIC.USER (E_MAIL, USER_PASSWORD, PHONE_NUMBER, USER_NAME)
VALUES ('TestUser@gmail.com', '$2a$10$2zYZwckcGtd/00RN.I48dOHnyIXqj5KLB3OLMVa3a2DYQeFHn6t2S', '+375337777777', 'TestUser');

//#########################################################################################
//                                  USER_ROLES
//#########################################################################################

INSERT INTO PUBLIC.USER_ROLES (USER_ID, ROLES_ID) VALUES (2, 1);

//#########################################################################################
//                                   BASE
//#########################################################################################

INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER) VALUES ('Большая', 2);
INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER) VALUES ('Средняя', 1.5);
INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER) VALUES ('Маленькая', 1);
INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER) VALUES ('Тонкая средняя', 1.2);
INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER) VALUES ('Тонкая большая', 1.8);
INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER) VALUES ('Кальцоне', 1.5);

//#########################################################################################
//                                PRODUCT CATEGORIES
//#########################################################################################

INSERT INTO PUBLIC.CATEGORY (NAME, CATEGORY_PRICE) VALUES ('Архив', 0);
INSERT INTO PUBLIC.CATEGORY (NAME, CATEGORY_PRICE) VALUES ('Своя', 14);
INSERT INTO PUBLIC.CATEGORY (NAME, CATEGORY_PRICE) VALUES ('Классика', 15);
INSERT INTO PUBLIC.CATEGORY (NAME, CATEGORY_PRICE) VALUES ('Премиум', 19);
INSERT INTO PUBLIC.CATEGORY (NAME, CATEGORY_PRICE) VALUES ('Любимые', 17);

//#########################################################################################
//                                INGREDIENTS
//#########################################################################################

INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SAUCE', 'Томатный соус', 2);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SAUCE', 'BBQ соус', 2.1);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SAUCE', 'Карри соус', 2.2);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SAUCE', 'Чесночный соус', 2.1);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('CHEESE', 'Моцарелла', 1);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('CHEESE', 'Чеддер', 1.5);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('CHEESE', 'Пармезан', 2);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('CHEESE', 'Дорблю', 2.2);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('CHEESE', 'Фета', 1.8);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('MEAT', 'Бекон', 3.5);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('MEAT', 'Телятина', 4);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('MEAT', 'Ветчина', 2.8);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('MEAT', 'Колбаски', 3);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('MEAT', 'Пепперони', 2.8);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('MEAT', 'Курица', 2.5);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('VEGETABLE', 'Томат', 1.5);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('VEGETABLE', 'Лук', 1);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('VEGETABLE', 'Оливки', 2);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('VEGETABLE', 'Шампиньоны', 1.8);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('VEGETABLE', 'Соленые огурцы', 1.6);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('VEGETABLE', 'Ананас', 2);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('VEGETABLE', 'Сладкий перец', 1.7);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('VEGETABLE', 'Халапеньо', 2);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SEAFOOD', 'Креветки', 2.1);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SEAFOOD', 'Кальмар', 2);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SEAFOOD', 'Мидии', 2);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SEAFOOD', 'Тунец', 2.5);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SEAFOOD', 'Анчоусы', 1.8);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SAUCE', 'Бургер соус', 2.4);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('CHEESE', 'Тофу', 2.5);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SAUCE', 'Сливочный соус', 2);

//#########################################################################################
//                                PRODUCTS
//#########################################################################################

INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ваша неповторимая пицца', 'База', null, 1, 2);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ваша неповторимая пицца', 'База', null, 2, 2);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ваша неповторимая пицца', 'База', null, 3, 2);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ваша неповторимая пицца', 'База', null, 4, 2);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ваша неповторимая пицца', 'База', null, 5, 2);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ваша неповторимая пицца', 'База', null, 6, 2);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Когда хочется полегче', 'Маргарита', 30, 1, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Когда хочется полегче', 'Маргарита', 22.5, 2, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Когда хочется полегче', 'Маргарита', 15, 3, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Когда хочется полегче', 'Маргарита', 18, 4, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Когда хочется полегче', 'Маргарита', 27, 5, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Когда хочется полегче', 'Маргарита', 22.5, 6, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Была в фильме про Человека Паука.', 'Пепперони', 30, 1, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Была в фильме про Человека Паука.', 'Пепперони', 22.5, 2, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Была в фильме про Человека Паука.', 'Пепперони', 15, 3, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Была в фильме про Человека Паука.', 'Пепперони', 18, 4, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Была в фильме про Человека Паука.', 'Пепперони', 27, 5, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Была в фильме про Человека Паука.', 'Пепперони', 22.5, 6, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Мы заботимся о вкусах всех наших клиентов.', 'Веганская', 30, 1, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Мы заботимся о вкусах всех наших клиентов.', 'Веганская', 22.5, 2, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Мы заботимся о вкусах всех наших клиентов.', 'Веганская', 15, 3, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Мы заботимся о вкусах всех наших клиентов.', 'Веганская', 18, 4, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Мы заботимся о вкусах всех наших клиентов.', 'Веганская', 27, 5, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Мы заботимся о вкусах всех наших клиентов.', 'Веганская', 22.5, 6, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Вкус студенческой жизни.', 'Ветчина и грибы', 30, 1, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Вкус студенческой жизни.', 'Ветчина и грибы', 22.5, 2, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Вкус студенческой жизни.', 'Ветчина и грибы', 15, 3, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Вкус студенческой жизни.', 'Ветчина и грибы', 18, 4, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Вкус студенческой жизни.', 'Ветчина и грибы', 27, 5, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Вкус студенческой жизни.', 'Ветчина и грибы', 22.5, 6, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Любимая пицца Гордона Рамзи.', 'Гавайская', 30, 1, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Любимая пицца Гордона Рамзи.', 'Гавайская', 22.5, 2, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Любимая пицца Гордона Рамзи.', 'Гавайская', 15, 3, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Любимая пицца Гордона Рамзи.', 'Гавайская', 18, 4, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Любимая пицца Гордона Рамзи.', 'Гавайская', 27, 5, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Любимая пицца Гордона Рамзи.', 'Гавайская', 22.5, 6, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пицца бати.', 'Фермерская', 30, 1, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пицца бати.', 'Фермерская', 22.5, 2, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пицца бати.', 'Фермерская', 15, 3, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пицца бати.', 'Фермерская', 18, 4, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пицца бати.', 'Фермерская', 27, 5, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пицца бати.', 'Фермерская', 22.5, 6, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Под пикничок вкусно очень.', 'Барбекю', 34, 1, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Под пикничок вкусно очень.', 'Барбекю', 25.5, 2, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Под пикничок вкусно очень.', 'Барбекю', 17, 3, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Под пикничок вкусно очень.', 'Барбекю', 20.4, 4, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Под пикничок вкусно очень.', 'Барбекю', 30.6, 5, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Под пикничок вкусно очень.', 'Барбекю', 25.5, 6, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('So HOT!', 'Острая', 34, 1, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('So HOT!', 'Острая', 25.5, 2, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('So HOT!', 'Острая', 17, 3, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('So HOT!', 'Острая', 20.4, 4, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('So HOT!', 'Острая', 30.6, 5, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('So HOT!', 'Острая', 25.5, 6, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Наш чесночный цыпленок.', 'Цыпленок', 34, 1, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Наш чесночный цыпленок.', 'Цыпленок', 25.5, 2, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Наш чесночный цыпленок.', 'Цыпленок', 17, 3, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Наш чесночный цыпленок.', 'Цыпленок', 20.4, 4, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Наш чесночный цыпленок.', 'Цыпленок', 30.6, 5, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Наш чесночный цыпленок.', 'Цыпленок', 25.5, 6, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('От карри только соус.', 'Карри', 34, 1, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('От карри только соус.', 'Карри', 25.5, 2, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('От карри только соус.', 'Карри', 17, 3, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('От карри только соус.', 'Карри', 20.4, 4, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('От карри только соус.', 'Карри', 30.6, 5, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('От карри только соус.', 'Карри', 25.5, 6, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Должна быть пицца с морепродуктами.', 'Креветки с ананасом', 34, 1, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Должна быть пицца с морепродуктами.', 'Креветки с ананасом', 25.5, 2, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Должна быть пицца с морепродуктами.', 'Креветки с ананасом', 17, 3, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Должна быть пицца с морепродуктами.', 'Креветки с ананасом', 20.4, 4, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Должна быть пицца с морепродуктами.', 'Креветки с ананасом', 30.6, 5, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Должна быть пицца с морепродуктами.', 'Креветки с ананасом', 25.5, 6, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Дас ист гут!', 'Баварская', 34, 1, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Дас ист гут!', 'Баварская', 25.5, 2, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Дас ист гут!', 'Баварская', 17, 3, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Дас ист гут!', 'Баварская', 20.4, 4, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Дас ист гут!', 'Баварская', 30.6, 5, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Дас ист гут!', 'Баварская', 25.5, 6, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Фирменная есть фирменная.', 'Фирменная', 38, 1, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Фирменная есть фирменная.', 'Фирменная', 28.5, 2, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Фирменная есть фирменная.', 'Фирменная', 19, 3, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Фирменная есть фирменная.', 'Фирменная', 22.8, 4, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Фирменная есть фирменная.', 'Фирменная', 34.2, 5, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Фирменная есть фирменная.', 'Фирменная', 28.5, 6, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Для тех, кто любит оливки.', 'Феерия', 38, 1, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Для тех, кто любит оливки.', 'Феерия', 28.5, 2, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Для тех, кто любит оливки.', 'Феерия', 19, 3, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Для тех, кто любит оливки.', 'Феерия', 22.8, 4, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Для тех, кто любит оливки.', 'Феерия', 34.2, 5, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Для тех, кто любит оливки.', 'Феерия', 28.5, 6, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ну да сытная, ну и что?', 'Сытная', 38, 1, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ну да сытная, ну и что?', 'Сытная', 28.5, 2, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ну да сытная, ну и что?', 'Сытная', 19, 3, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ну да сытная, ну и что?', 'Сытная', 22.8, 4, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ну да сытная, ну и что?', 'Сытная', 34.2, 5, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ну да сытная, ну и что?', 'Сытная', 28.5, 6, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Целых ШЕСТЬ сыров!', '6 Сыров', 38, 1, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Целых ШЕСТЬ сыров!', '6 Сыров', 28.5, 2, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Целых ШЕСТЬ сыров!', '6 Сыров', 19, 3, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Целых ШЕСТЬ сыров!', '6 Сыров', 22.8, 4, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Целых ШЕСТЬ сыров!', '6 Сыров', 34.2, 5, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Целых ШЕСТЬ сыров!', '6 Сыров', 28.5, 6, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Наш ответ Макдональдс.', 'Бургер', 38, 1, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Наш ответ Макдональдс.', 'Бургер', 28.5, 2, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Наш ответ Макдональдс.', 'Бургер', 19, 3, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Наш ответ Макдональдс.', 'Бургер', 22.8, 4, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Наш ответ Макдональдс.', 'Бургер', 34.2, 5, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Наш ответ Макдональдс.', 'Бургер', 28.5, 6, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Данке шон!', 'Мюнхенская', 38, 1, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Данке шон!', 'Мюнхенская', 28.5, 2, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Данке шон!', 'Мюнхенская', 19, 3, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Данке шон!', 'Мюнхенская', 22.8, 4, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Данке шон!', 'Мюнхенская', 34.2, 5, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Данке шон!', 'Мюнхенская', 28.5, 6, 1);

//#########################################################################################
//                                PRODUCT-INGREDIENT
//#########################################################################################

INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (7, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (7, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (8, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (8, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (9, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (9, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (10, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (10, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (11, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (11, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (12, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (12, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (13, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (13, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (13, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (14, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (14, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (14, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (15, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (15, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (15, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (16, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (16, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (16, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (17, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (17, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (17, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (18, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (18, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (18, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (19, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (19, 30);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (19, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (19, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (19, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (19, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (19, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (20, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (20, 30);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (20, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (20, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (20, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (20, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (20, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (21, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (21, 30);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (21, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (21, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (21, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (21, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (21, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (22, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (22, 30);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (22, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (22, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (22, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (22, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (22, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (23, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (23, 30);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (23, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (23, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (23, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (23, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (23, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (24, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (24, 30);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (24, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (24, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (24, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (24, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (24, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (25, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (25, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (25, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (25, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (26, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (26, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (26, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (26, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (27, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (27, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (27, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (27, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (28, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (28, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (28, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (28, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (29, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (29, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (29, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (29, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (30, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (30, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (30, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (30, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (31, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (31, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (31, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (31, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (32, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (32, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (32, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (32, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (33, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (33, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (33, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (33, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (34, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (34, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (34, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (34, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (35, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (35, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (35, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (35, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (36, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (36, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (36, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (36, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (37, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (37, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (37, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (37, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (38, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (38, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (38, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (38, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (39, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (39, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (39, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (39, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (40, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (40, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (40, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (40, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (41, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (41, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (41, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (41, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (42, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (42, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (42, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (42, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (43, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (43, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (43, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (43, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (43, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (43, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (44, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (44, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (44, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (44, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (44, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (44, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (45, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (45, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (45, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (45, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (45, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (45, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (46, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (46, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (46, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (46, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (46, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (46, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (47, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (47, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (47, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (47, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (47, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (47, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (48, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (48, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (48, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (48, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (48, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (48, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (49, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (49, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (49, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (49, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (49, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (49, 23);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (50, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (50, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (50, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (50, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (50, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (50, 23);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (51, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (51, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (51, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (51, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (51, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (51, 23);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (52, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (52, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (52, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (52, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (52, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (52, 23);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (53, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (53, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (53, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (53, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (53, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (53, 23);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (54, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (54, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (54, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (54, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (54, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (54, 23);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (55, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (55, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (55, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (55, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (55, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (55, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (56, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (56, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (56, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (56, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (56, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (56, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (57, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (57, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (57, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (57, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (57, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (57, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (58, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (58, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (58, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (58, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (58, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (58, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (59, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (59, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (59, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (59, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (59, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (59, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (60, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (60, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (60, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (60, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (60, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (60, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (61, 3);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (61, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (61, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (61, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (61, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (62, 3);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (62, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (62, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (62, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (62, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (63, 3);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (63, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (63, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (63, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (63, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (64, 3);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (64, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (64, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (64, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (64, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (65, 3);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (65, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (65, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (65, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (65, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (66, 3);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (66, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (66, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (66, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (66, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (67, 31);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (67, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (67, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (67, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (67, 24);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (68, 31);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (68, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (68, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (68, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (68, 24);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (69, 31);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (69, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (69, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (69, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (69, 24);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (70, 31);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (70, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (70, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (70, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (70, 24);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (71, 31);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (71, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (71, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (71, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (71, 24);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (72, 31);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (72, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (72, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (72, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (72, 24);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (73, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (73, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (73, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (73, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (73, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (73, 23);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (74, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (74, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (74, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (74, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (74, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (74, 23);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (75, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (75, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (75, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (75, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (75, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (75, 23);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (76, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (76, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (76, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (76, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (76, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (76, 23);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (77, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (77, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (77, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (77, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (77, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (77, 23);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (78, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (78, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (78, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (78, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (78, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (78, 23);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (79, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (79, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (79, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (79, 30);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (79, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (79, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (79, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (79, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (79, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (80, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (80, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (80, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (80, 30);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (80, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (80, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (80, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (80, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (80, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (81, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (81, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (81, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (81, 30);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (81, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (81, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (81, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (81, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (81, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (82, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (82, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (82, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (82, 30);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (82, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (82, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (82, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (82, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (82, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (83, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (83, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (83, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (83, 30);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (83, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (83, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (83, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (83, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (83, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (84, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (84, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (84, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (84, 30);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (84, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (84, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (84, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (84, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (84, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (91, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (91, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (91, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (91, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (91, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (91, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (91, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (91, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (91, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (91, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (92, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (92, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (92, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (92, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (92, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (92, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (92, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (92, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (92, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (92, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (93, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (93, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (93, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (93, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (93, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (93, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (93, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (93, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (93, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (93, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (94, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (94, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (94, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (94, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (94, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (94, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (94, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (94, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (94, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (94, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (95, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (95, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (95, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (95, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (95, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (95, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (95, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (95, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (95, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (95, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (96, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (96, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (96, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (96, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (96, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (96, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (96, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (96, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (96, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (96, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (97, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (97, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (97, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (97, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (97, 8);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (97, 9);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (98, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (98, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (98, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (98, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (98, 8);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (98, 9);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (99, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (99, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (99, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (99, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (99, 8);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (99, 9);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (100, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (100, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (100, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (100, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (100, 8);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (100, 9);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (101, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (101, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (101, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (101, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (101, 8);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (101, 9);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (102, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (102, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (102, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (102, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (102, 8);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (102, 9);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (103, 29);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (103, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (103, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (103, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (103, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (103, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (103, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (103, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (104, 29);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (104, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (104, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (104, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (104, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (104, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (104, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (104, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (105, 29);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (105, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (105, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (105, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (105, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (105, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (105, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (105, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (106, 29);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (106, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (106, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (106, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (106, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (106, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (106, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (106, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (107, 29);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (107, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (107, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (107, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (107, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (107, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (107, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (107, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (108, 29);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (108, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (108, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (108, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (108, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (108, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (108, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (108, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (109, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (109, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (109, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (109, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (109, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (109, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (109, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (110, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (110, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (110, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (110, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (110, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (110, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (110, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (111, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (111, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (111, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (111, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (111, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (111, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (111, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (112, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (112, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (112, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (112, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (112, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (112, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (112, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (113, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (113, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (113, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (113, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (113, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (113, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (113, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (114, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (114, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (114, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (114, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (114, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (114, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (114, 19);

//#########################################################################################
//                                BASKET
//#########################################################################################

INSERT INTO PUBLIC.BASKET (IS_ACTIVE, TIME, USER_ID) VALUES (false, '2021-03-05 17:17:00.000000', 2);
INSERT INTO PUBLIC.BASKET (IS_ACTIVE, TIME, USER_ID) VALUES (false, '2021-03-05 18:28:00.000000', 2);
INSERT INTO PUBLIC.BASKET (IS_ACTIVE, TIME, USER_ID) VALUES (false, '2021-03-05 18:28:00.000000', 2);
INSERT INTO PUBLIC.BASKET (IS_ACTIVE, TIME, USER_ID) VALUES (false, '2021-03-05 18:29:00.000000', 2);
INSERT INTO PUBLIC.BASKET (IS_ACTIVE, TIME, USER_ID) VALUES (true, '2021-03-05 18:31:00.000000', 2);

//#########################################################################################
//                                BASKET_ITEM
//#########################################################################################

INSERT INTO PUBLIC.BASKET_ITEM (DESCRIPTION, PRICE, BASKET_ID, PRODUCT_ID) VALUES ('', 30, 2, 13);
INSERT INTO PUBLIC.BASKET_ITEM (DESCRIPTION, PRICE, BASKET_ID, PRODUCT_ID) VALUES ('', 38, 3, 97);
INSERT INTO PUBLIC.BASKET_ITEM (DESCRIPTION, PRICE, BASKET_ID, PRODUCT_ID) VALUES ('Ингридиенты: Карри соус, Моцарелла, Чеддер, Телятина, Ветчина, Халапеньо.', 27.5, 3, 3);
INSERT INTO PUBLIC.BASKET_ITEM (DESCRIPTION, PRICE, BASKET_ID, PRODUCT_ID) VALUES ('', 19, 4, 93);
INSERT INTO PUBLIC.BASKET_ITEM (DESCRIPTION, PRICE, BASKET_ID, PRODUCT_ID) VALUES ('', 25.5, 5, 44);
INSERT INTO PUBLIC.BASKET_ITEM (DESCRIPTION, PRICE, BASKET_ID, PRODUCT_ID) VALUES ('', 38, 5, 103);
INSERT INTO PUBLIC.BASKET_ITEM (DESCRIPTION, PRICE, BASKET_ID, PRODUCT_ID) VALUES ('', 15, 5, 33);

//#########################################################################################
//                                ORDERS
//#########################################################################################

INSERT INTO PUBLIC.ORDERS (COMMENT, PHONE_NUMBER, PRICE, STATUS, TIME, TYPE_OF_PAYMENT, USER_ID)
VALUES ('', '+375337777777', 30, 'PAID', '2021-03-05 18:28:00.000000', 'CASH', 2);
INSERT INTO PUBLIC.ORDERS (COMMENT, PHONE_NUMBER, PRICE, STATUS, TIME, TYPE_OF_PAYMENT, USER_ID)
VALUES ('Заказ на завтра к 12:00', '+375337777777', 65.5, 'PAID', '2021-03-05 18:28:00.000000', 'ONLINE', 2);
INSERT INTO PUBLIC.ORDERS (COMMENT, PHONE_NUMBER, PRICE, STATUS, TIME, TYPE_OF_PAYMENT, USER_ID)
VALUES ('Приготовить к 20:30', '+375337777777', 19, 'CANCELED', '2021-03-05 18:29:00.000000', 'CASH', 2);
INSERT INTO PUBLIC.ORDERS (COMMENT, PHONE_NUMBER, PRICE, STATUS, TIME, TYPE_OF_PAYMENT, USER_ID)
VALUES ('', '+375259658731', 78.5, 'NOT_PAID', '2021-03-05 18:31:00.000000', 'CASH', 2);

//#########################################################################################
//                                ORDER_ITEM
//#########################################################################################

INSERT INTO PUBLIC.ORDER_ITEM (DESCRIPTION, PRICE, ORDER_ID, PRODUCT_ID) VALUES ('', 30, 1, 13);
INSERT INTO PUBLIC.ORDER_ITEM (DESCRIPTION, PRICE, ORDER_ID, PRODUCT_ID) VALUES ('', 38, 2, 97);
INSERT INTO PUBLIC.ORDER_ITEM (DESCRIPTION, PRICE, ORDER_ID, PRODUCT_ID)
VALUES ('Ингридиенты: Карри соус, Моцарелла, Чеддер, Телятина, Ветчина, Халапеньо.', 27.5, 2, 3);
INSERT INTO PUBLIC.ORDER_ITEM (DESCRIPTION, PRICE, ORDER_ID, PRODUCT_ID) VALUES ('', 19, 3, 93);
INSERT INTO PUBLIC.ORDER_ITEM (DESCRIPTION, PRICE, ORDER_ID, PRODUCT_ID) VALUES ('', 25.5, 4, 44);
INSERT INTO PUBLIC.ORDER_ITEM (DESCRIPTION, PRICE, ORDER_ID, PRODUCT_ID) VALUES ('', 38, 4, 103);
INSERT INTO PUBLIC.ORDER_ITEM (DESCRIPTION, PRICE, ORDER_ID, PRODUCT_ID) VALUES ('', 15, 4, 33);

