-- INSERT INTO public.roles(id, name)
-- VALUES (1, 'ROLE_USER'),
--        (2, 'ROLE_ADMIN');
--

create table ROLES
(
    ID   BIGINT auto_increment
        primary key,
    NAME VARCHAR(255) not null
);

create table USER
(
    ID            BIGINT auto_increment
        primary key,
    E_MAIL        VARCHAR(255) not null,
    USER_PASSWORD VARCHAR(255) not null,
    PHONE_NUMBER  VARCHAR(255),
    USER_NAME     VARCHAR(255) not null
);

create table USER_ROLES
(
    USER_ID  BIGINT not null,
    ROLES_ID BIGINT not null,
    primary key (USER_ID, ROLES_ID),
  --  constraint FKDBV8TDYLTXA1QJMFNJ9OBOXSE
        foreign key (ROLES_ID) references ROLES (ID),
    --constraint FKLCR6K906EY81VMTKYPH9UHD64
        foreign key (USER_ID) references USER (ID)
);



create table BASE
(
    ID               SMALLINT auto_increment
        primary key,
    NAME             VARCHAR(255) not null,
    PRICE_MULTIPLIER DOUBLE       not null
);

create table BASKET
(
    ID        BIGINT auto_increment
        primary key,
    IS_ACTIVE BOOLEAN   not null,
    TIME      TIMESTAMP not null,
    USER_ID   BIGINT    not null,
   -- constraint FKFP7YINN3DH4SY1IA364XP3D9G
        foreign key (USER_ID) references USER (ID)
);

create table CATEGORY
(
    ID             SMALLINT auto_increment
        primary key,
    NAME           VARCHAR(255) not null,
    CATEGORY_PRICE DOUBLE       not null
);

create table INGREDIENT
(
    ID              SMALLINT auto_increment
        primary key,
    INGREDIENT_TYPE VARCHAR(255) not null,
    NAME            VARCHAR(255) not null,
    PRICE           DOUBLE       not null
);

create table PRODUCT
(
    ID          BIGINT auto_increment
        primary key,
    DESCRIPTION VARCHAR(255),
    NAME        VARCHAR(255) not null,
    PRICE       DOUBLE,
    BASE_ID     SMALLINT     not null,
    CATEGORY_ID SMALLINT,
--     constraint FKEXQQEAKSNMMKU5PY194YWP140
    foreign key (CATEGORY_ID) references CATEGORY (ID),
--     constraint FKGL5150TTV6L4CJSRDMANL6Q97
    foreign key (BASE_ID) references BASE (ID)
);

create table PRODUCT_INGREDIENT
(
    PRODUCT_ID    BIGINT   not null,
    INGREDIENT_ID SMALLINT not null,
    -- constraint FKH4NW56RHG770KEHBQTTGFRCGN
    foreign key (PRODUCT_ID) references PRODUCT (ID),
    --  constraint FKQWNOR4910RLI2NVL4PXGLVS85
    foreign key (INGREDIENT_ID) references INGREDIENT (ID)
);

create table BASKET_ITEM
(
    ID          BIGINT auto_increment
        primary key,
    DESCRIPTION VARCHAR(255),
    PRICE       DOUBLE not null,
    BASKET_ID   BIGINT not null,
    PRODUCT_ID  BIGINT not null,
  --  constraint FKARA19F2XV7ML3A24F50V6BSK2
        foreign key (BASKET_ID) references BASKET (ID),
  --  constraint FKMQOVAFSU48HKGBHO5V5KNTHD3
        foreign key (PRODUCT_ID) references PRODUCT (ID)
);

create table ORDERS
(
    ID              BIGINT auto_increment
        primary key,
    COMMENT         VARCHAR(255),
    PHONE_NUMBER    VARCHAR(255) not null,
    PRICE           DOUBLE,
    STATUS          VARCHAR(255) not null,
    TIME            TIMESTAMP    not null,
    TYPE_OF_PAYMENT VARCHAR(255),
    USER_ID         BIGINT       not null,
   -- constraint FKEL9KYL84EGO2OTJ2ACCFD8MR7
        foreign key (USER_ID) references USER (ID)
);

create table ORDER_ITEM
(
    ID          BIGINT auto_increment
        primary key,
    DESCRIPTION VARCHAR(255),
    PRICE       DOUBLE,
    ORDER_ID    BIGINT not null,
    PRODUCT_ID  BIGINT not null,
  --  constraint FK6XYEQUV6TP9T8C10GI3CXNQL1
        foreign key (PRODUCT_ID) references PRODUCT (ID),
--    constraint FKT4DC2R9NBVBUJRLJV3E23IIBT
        foreign key (ORDER_ID) references ORDERS (ID)
);

INSERT INTO PUBLIC.ROLES (NAME) VALUES ('ROLE_USER');
INSERT INTO PUBLIC.ROLES (NAME) VALUES ('ROLE_ADMIN');

//#########################################################################################
//                                BASES FOR PRODUCTS
//#########################################################################################

INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER)
VALUES ('Большая', 2);
INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER)
VALUES ('Средняя', 1.5);
INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER)
VALUES ('Маленькая', 1);
INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER)
VALUES ('Тонкая средняя', 1.2);
INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER)
VALUES ('Тонкая большая', 1.8);
INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER)
VALUES ('Кальцоне', 1.5);


-- INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER)
-- VALUES ('Большая', 2.0),
--        ('Средняя', 1.5),
--        ('Маленькая', 1.0),
--        ('Тонкая средняя', 1.2),
--        ('Тонкая большая', 1.8),
--        ('Кальцоне', 1.5);
//#########################################################################################
//                                PRODUCT CATEGORIES
//#########################################################################################


INSERT INTO PUBLIC.CATEGORY (NAME, CATEGORY_PRICE)
VALUES ('Архив', 0);
INSERT INTO PUBLIC.CATEGORY (NAME, CATEGORY_PRICE)
VALUES ('Своя', 16);
INSERT INTO PUBLIC.CATEGORY (NAME, CATEGORY_PRICE)
VALUES ('Классика', 15);
INSERT INTO PUBLIC.CATEGORY (NAME, CATEGORY_PRICE)
VALUES ('Премиум', 19);
INSERT INTO PUBLIC.CATEGORY (NAME, CATEGORY_PRICE)
VALUES ('Любимые', 17);


-- INSERT INTO PUBLIC.CATEGORY (NAME, CATEGORY_PRICE)
-- VALUES ('Архив', 0.0),
--        ('Своя', 17.0);
//#########################################################################################
//                                PRODUCT INGREDIENTS
//#########################################################################################



INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SAUCE', 'Томатный соус', 2);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SAUCE', 'BBQ соус', 2.1);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SAUCE', 'Карри соус', 2.2);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SAUCE', 'Чесночный соус', 2.1);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('CHEESE', 'Моцарелла', 1);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('CHEESE', 'Чеддер', 1.5);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('CHEESE', 'Пармезан', 2);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('CHEESE', 'Дорблю', 2.2);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('CHEESE', 'Фета', 1.8);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('MEAT', 'Бекон', 3.5);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('MEAT', 'Телятина', 4);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('MEAT', 'Ветчина', 2.8);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('MEAT', 'Колбаски', 3);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('MEAT', 'Пепперони', 2.8);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('MEAT', 'Курица', 2.5);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('VEGETABLE', 'Томат', 1.5);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('VEGETABLE', 'Лук', 1);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('VEGETABLE', 'Оливки', 2);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('VEGETABLE', 'Шампиньоны', 1.8);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('VEGETABLE', 'Соленые огурцы', 1.6);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('VEGETABLE', 'Ананас', 2);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('VEGETABLE', 'Сладкий перец', 1.7);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('VEGETABLE', 'Халапеньо', 2);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SEAFOOD', 'Креветки', 2.1);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SEAFOOD', 'Кальмар', 2);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SEAFOOD', 'Мидии', 2);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SEAFOOD', 'Тунец', 2.5);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SEAFOOD', 'Анчоусы', 1.8);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SAUCE', 'Бургер соус', 2.4);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('CHEESE', 'Тофу', 2.5);
INSERT INTO PUBLIC.INGREDIENT (INGREDIENT_TYPE, NAME, PRICE) VALUES ('SAUCE', 'Сливочный соус', 2);





-- INSERT INTO PUBLIC.INGREDIENT (NAME, PRICE, INGREDIENT_TYPE)
-- VALUES
--        //sauces
--        ('Томатный соус', 2, 'SAUCE'),
--        ('BBQ соус', 2.1, 'SAUCE'),
--        ('Карри соус', 2.2, 'SAUCE'),
--        ('Чесночный соус', 2.1, 'SAUCE'),
--        //cheeses
--        ('Моцарелла', 1.0, 'CHEESE'),
--        ('Чеддер', 1.5, 'CHEESE'),
--        ('Пармезан', 2.0, 'CHEESE'),
--        ('Дорблю', 2.2,'CHEESE'),
--        ('Фета', 1.8, 'CHEESE'),
--        //meat
--        ('Бекон', 3.5, 'MEAT'),
--        ('Телятина', 4, 'MEAT'),
--        ('Ветчина', 2.8, 'MEAT'),
--        ('Колбаски', 3.0, 'MEAT'),
--        ('Пепперони', 2.8, 'MEAT'),
--        ('Курица', 2.5, 'MEAT'),
--        //vegetable
--        ('Томат', 1.5, 'VEGETABLE'),
--        ('Лук', 1, 'VEGETABLE'),
--        ('Оливки', 2, 'VEGETABLE'),
--        ('Шампиньоны', 1.8, 'VEGETABLE'),
--        ('Соленые огурцы', 1.6, 'VEGETABLE'),
--        ('Ананас', 2, 'VEGETABLE'),
--        ('Сладкий перец', 1.7, 'VEGETABLE'),
--        ('Халапеньо', 2, 'VEGETABLE'),
--        //seafood
--        ('Креветки', 2.1, 'SEAFOOD'),
--        ('Кальмар', 2.0, 'SEAFOOD'),
--        ('Мидии', 2.0, 'SEAFOOD'),
--        ('Тунец', 2.5, 'SEAFOOD'),
--        ('Анчоусы', 1.8, 'SEAFOOD');

//#########################################################################################
//                                PRODUCTS
//#########################################################################################


INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ваша неповторимая пицца', 'База', null, 1, 2);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ваша неповторимая пицца', 'База', null, 2, 2);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ваша неповторимая пицца', 'База', null, 3, 2);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ваша неповторимая пицца', 'База', null, 4, 2);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ваша неповторимая пицца', 'База', null, 5, 2);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ваша неповторимая пицца', 'База', null, 6, 2);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Бессмертная классика', 'Пепперони', 30, 1, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Бессмертная классика', 'Пепперони', 22.5, 2, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Бессмертная классика', 'Пепперони', 15, 3, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Бессмертная классика', 'Пепперони', 18, 4, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Бессмертная классика', 'Пепперони', 27, 5, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Бессмертная классика', 'Пепперони', 22.5, 6, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Любимый выбор студентов.', 'Ветчина и грибы', 30, 1, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Любимый выбор студентов.', 'Ветчина и грибы', 22.5, 2, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Любимый выбор студентов.', 'Ветчина и грибы', 15, 3, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Любимый выбор студентов.', 'Ветчина и грибы', 18, 4, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Любимый выбор студентов.', 'Ветчина и грибы', 27, 5, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Любимый выбор студентов.', 'Ветчина и грибы', 22.5, 6, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Мы заботимся обо всех наших гостях и их вкусах', 'Вегетерианская', 30, 1, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Мы заботимся обо всех наших гостях и их вкусах', 'Вегетерианская', 22.5, 2, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Мы заботимся обо всех наших гостях и их вкусах', 'Вегетерианская', 15, 3, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Мы заботимся обо всех наших гостях и их вкусах', 'Вегетерианская', 18, 4, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Мы заботимся обо всех наших гостях и их вкусах', 'Вегетерианская', 27, 5, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Мы заботимся обо всех наших гостях и их вкусах', 'Вегетерианская', 22.5, 6, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Простота иногда уместна', 'Маргарита', 30, 1, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Простота иногда уместна', 'Маргарита', 22.5, 2, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Простота иногда уместна', 'Маргарита', 15, 3, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Простота иногда уместна', 'Маргарита', 18, 4, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Простота иногда уместна', 'Маргарита', 27, 5, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Простота иногда уместна', 'Маргарита', 22.5, 6, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('На пикник самое оно', 'Барбекю', 34, 1, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('На пикник самое оно', 'Барбекю', 25.5, 2, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('На пикник самое оно', 'Барбекю', 17, 3, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('На пикник самое оно', 'Барбекю', 20.4, 4, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('На пикник самое оно', 'Барбекю', 30.6, 5, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('На пикник самое оно', 'Барбекю', 25.5, 6, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Для любителей морепродуктов', 'Креветки с ананасом', 34, 1, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Для любителей морепродуктов', 'Креветки с ананасом', 25.5, 2, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Для любителей морепродуктов', 'Креветки с ананасом', 17, 3, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Для любителей морепродуктов', 'Креветки с ананасом', 20.4, 4, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Для любителей морепродуктов', 'Креветки с ананасом', 30.6, 5, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Для любителей морепродуктов', 'Креветки с ананасом', 25.5, 6, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Что бы сказал Гордон Рамзи?!', 'Гавайская', 30, 1, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Что бы сказал Гордон Рамзи?!', 'Гавайская', 22.5, 2, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Что бы сказал Гордон Рамзи?!', 'Гавайская', 15, 3, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Что бы сказал Гордон Рамзи?!', 'Гавайская', 18, 4, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Что бы сказал Гордон Рамзи?!', 'Гавайская', 27, 5, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Что бы сказал Гордон Рамзи?!', 'Гавайская', 22.5, 6, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пощипать рецепторы', 'Острая', 34, 1, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пощипать рецепторы', 'Острая', 25.5, 2, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пощипать рецепторы', 'Острая', 17, 3, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пощипать рецепторы', 'Острая', 20.4, 4, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пощипать рецепторы', 'Острая', 30.6, 5, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пощипать рецепторы', 'Острая', 25.5, 6, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Спасибо ребятам из инди за соус и за туториалы на ютубе.', 'Карри', 34, 1, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Спасибо ребятам из инди за соус и за туториалы на ютубе.', 'Карри', 25.5, 2, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Спасибо ребятам из инди за соус и за туториалы на ютубе.', 'Карри', 17, 3, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Спасибо ребятам из инди за соус и за туториалы на ютубе.', 'Карри', 20.4, 4, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Спасибо ребятам из инди за соус и за туториалы на ютубе.', 'Карри', 30.6, 5, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Спасибо ребятам из инди за соус и за туториалы на ютубе.', 'Карри', 25.5, 6, 5);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Как Биг тейсти', 'Бургер', 34, 1, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Как Биг тейсти', 'Бургер', 25.5, 2, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Как Биг тейсти', 'Бургер', 17, 3, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Как Биг тейсти', 'Бургер', 20.4, 4, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Как Биг тейсти', 'Бургер', 30.6, 5, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Как Биг тейсти', 'Бургер', 25.5, 6, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Моя любимая', 'Феерия', 38, 1, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Моя любимая', 'Феерия', 28.5, 2, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Моя любимая', 'Феерия', 19, 3, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Моя любимая', 'Феерия', 22.8, 4, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Моя любимая', 'Феерия', 34.2, 5, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Моя любимая', 'Феерия', 28.5, 6, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ну сытная и сытная', 'Сытная', 38, 1, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ну сытная и сытная', 'Сытная', 28.5, 2, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ну сытная и сытная', 'Сытная', 19, 3, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ну сытная и сытная', 'Сытная', 22.8, 4, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ну сытная и сытная', 'Сытная', 34.2, 5, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Ну сытная и сытная', 'Сытная', 28.5, 6, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('5 Серов', '5 Сыров', 38, 1, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('5 Серов', '5 Сыров', 28.5, 2, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('5 Серов', '5 Сыров', 19, 3, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('5 Серов', '5 Сыров', 22.8, 4, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('5 Серов', '5 Сыров', 34.2, 5, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('5 Серов', '5 Сыров', 28.5, 6, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Фирменная на то и фирменная', 'Фирменная', 38, 1, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Фирменная на то и фирменная', 'Фирменная', 28.5, 2, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Фирменная на то и фирменная', 'Фирменная', 19, 3, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Фирменная на то и фирменная', 'Фирменная', 22.8, 4, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Фирменная на то и фирменная', 'Фирменная', 34.2, 5, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Фирменная на то и фирменная', 'Фирменная', 28.5, 6, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пот пиво берите - не прогадаете', 'Мюнхенская', 38, 1, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пот пиво берите - не прогадаете', 'Мюнхенская', 28.5, 2, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пот пиво берите - не прогадаете', 'Мюнхенская', 19, 3, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пот пиво берите - не прогадаете', 'Мюнхенская', 22.8, 4, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пот пиво берите - не прогадаете', 'Мюнхенская', 34.2, 5, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пот пиво берите - не прогадаете', 'Мюнхенская', 28.5, 6, 4);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пицца бати', 'Фермерская', 30, 1, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пицца бати', 'Фермерская', 22.5, 2, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пицца бати', 'Фермерская', 15, 3, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пицца бати', 'Фермерская', 18, 4, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пицца бати', 'Фермерская', 27, 5, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Пицца бати', 'Фермерская', 22.5, 6, 3);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Странная пицца, опасная', 'Цыпленок', 30, 1, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Странная пицца, опасная', 'Цыпленок', 22.5, 2, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Странная пицца, опасная', 'Цыпленок', 15, 3, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Странная пицца, опасная', 'Цыпленок', 18, 4, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Странная пицца, опасная', 'Цыпленок', 27, 5, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Странная пицца, опасная', 'Цыпленок', 22.5, 6, 1);

-- INSERT INTO PUBLIC.PRODUCT (NAME, BASE_ID, DESCRIPTION, CATEGORY_ID) VALUES
-- ('База', 1, 'Ваша неповторимая пицца', 2),
-- ('База', 2,'Ваша неповторимая пицца', 2),
-- ('База', 3,'Ваша неповторимая пицца', 2),
-- ('База', 4,'Ваша неповторимая пицца', 2),
-- ('База', 5,'Ваша неповторимая пицца', 2),
-- ('База', 6,'Ваша неповторимая пицца', 2);




INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (13, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (13, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (13, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (14, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (14, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (14, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (15, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (15, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (15, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (16, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (16, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (16, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (17, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (17, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (17, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (18, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (18, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (18, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (19, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (20, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (21, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (22, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (23, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (24, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (73, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (73, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (73, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (73, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (74, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (74, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (74, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (74, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (75, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (75, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (75, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (75, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (76, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (76, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (76, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (76, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (77, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (77, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (77, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (77, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (78, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (78, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (78, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (78, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (85, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (86, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (87, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (88, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (89, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (90, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (7, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (7, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (7, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (8, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (8, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (8, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (9, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (9, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (9, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (10, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (10, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (10, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (11, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (11, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (11, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (12, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (12, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (12, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (25, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (25, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (25, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (25, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (26, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (26, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (26, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (26, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (27, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (27, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (27, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (27, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (28, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (28, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (28, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (28, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (29, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (29, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (29, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (29, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (30, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (30, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (30, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (30, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (31, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (31, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (31, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (31, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (31, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (31, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (31, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (32, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (32, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (32, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (32, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (32, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (32, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (32, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (33, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (33, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (33, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (33, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (33, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (33, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (33, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (34, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (34, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (34, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (34, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (34, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (34, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (34, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (35, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (35, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (35, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (35, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (35, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (35, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (35, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (36, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (36, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (36, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (36, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (36, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (36, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (36, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (37, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (37, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (38, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (38, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (39, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (39, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (40, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (40, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (41, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (41, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (42, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (42, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (55, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (55, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (55, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (55, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (55, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (56, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (56, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (56, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (56, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (56, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (57, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (57, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (57, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (57, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (57, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (58, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (58, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (58, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (58, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (58, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (59, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (59, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (59, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (59, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (59, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (60, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (60, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (60, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (60, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (60, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (43, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (43, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (43, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (43, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (43, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (43, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (44, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (44, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (44, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (44, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (44, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (44, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (45, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (45, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (45, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (45, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (45, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (45, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (46, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (46, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (46, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (46, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (46, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (46, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (47, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (47, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (47, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (47, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (47, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (47, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (48, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (48, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (48, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (48, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (48, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (48, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (49, 31);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (49, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (49, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (49, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (49, 24);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (50, 31);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (50, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (50, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (50, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (50, 24);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (51, 31);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (51, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (51, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (51, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (51, 24);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (52, 31);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (52, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (52, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (52, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (52, 24);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (53, 31);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (53, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (53, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (53, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (53, 24);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (54, 31);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (54, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (54, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (54, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (54, 24);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (61, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (61, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (61, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (61, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (61, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (61, 23);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (62, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (62, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (62, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (62, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (62, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (62, 23);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (63, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (63, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (63, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (63, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (63, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (63, 23);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (64, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (64, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (64, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (64, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (64, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (64, 23);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (65, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (65, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (65, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (65, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (65, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (65, 23);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (66, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (66, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (66, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (66, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (66, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (66, 23);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (67, 3);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (67, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (67, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (67, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (67, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (68, 3);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (68, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (68, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (68, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (68, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (69, 3);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (69, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (69, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (69, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (69, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (70, 3);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (70, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (70, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (70, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (70, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (71, 3);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (71, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (71, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (71, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (71, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (72, 3);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (72, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (72, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (72, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (72, 21);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (79, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (79, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (79, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (79, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (79, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (79, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (79, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (79, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (79, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (80, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (80, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (80, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (80, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (80, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (80, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (80, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (80, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (80, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (81, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (81, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (81, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (81, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (81, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (81, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (81, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (81, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (81, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (82, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (82, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (82, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (82, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (82, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (82, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (82, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (82, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (82, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (83, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (83, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (83, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (83, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (83, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (83, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (83, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (83, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (83, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (84, 1);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (84, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (84, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (84, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (84, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (84, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (84, 18);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (84, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (84, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (91, 31);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (91, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (91, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (91, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (91, 8);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (91, 9);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (92, 31);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (92, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (92, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (92, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (92, 8);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (92, 9);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (93, 31);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (93, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (93, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (93, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (93, 8);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (93, 9);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (94, 31);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (94, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (94, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (94, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (94, 8);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (94, 9);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (95, 31);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (95, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (95, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (95, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (95, 8);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (95, 9);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (96, 31);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (96, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (96, 6);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (96, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (96, 8);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (96, 9);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (109, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (109, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (109, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (109, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (110, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (110, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (110, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (110, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (111, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (111, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (111, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (111, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (112, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (112, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (112, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (112, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (113, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (113, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (113, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (113, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (114, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (114, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (114, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (114, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (97, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (97, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (97, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (97, 30);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (97, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (97, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (97, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (97, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (97, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (97, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (98, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (98, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (98, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (98, 30);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (98, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (98, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (98, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (98, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (98, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (98, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (99, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (99, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (99, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (99, 30);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (99, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (99, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (99, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (99, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (99, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (99, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (100, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (100, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (100, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (100, 30);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (100, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (100, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (100, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (100, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (100, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (100, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (101, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (101, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (101, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (101, 30);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (101, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (101, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (101, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (101, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (101, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (101, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (102, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (102, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (102, 7);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (102, 30);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (102, 10);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (102, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (102, 14);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (102, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (102, 19);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (102, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (103, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (103, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (103, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (103, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (103, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (103, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (103, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (103, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (104, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (104, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (104, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (104, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (104, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (104, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (104, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (104, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (105, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (105, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (105, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (105, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (105, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (105, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (105, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (105, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (106, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (106, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (106, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (106, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (106, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (106, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (106, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (106, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (107, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (107, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (107, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (107, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (107, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (107, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (107, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (107, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (108, 2);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (108, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (108, 11);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (108, 12);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (108, 13);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (108, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (108, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (108, 17);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (115, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (115, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (115, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (115, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (115, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (115, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (116, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (116, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (116, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (116, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (116, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (116, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (117, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (117, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (117, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (117, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (117, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (117, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (118, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (118, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (118, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (118, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (118, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (118, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (119, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (119, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (119, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (119, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (119, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (119, 22);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (120, 4);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (120, 5);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (120, 15);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (120, 16);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (120, 20);
INSERT INTO PUBLIC.PRODUCT_INGREDIENT (PRODUCT_ID, INGREDIENT_ID) VALUES (120, 22);
