INSERT INTO PUBLIC.BASE (NAME, PRICE) VALUES ('Большая', 2.5);
INSERT INTO PUBLIC.BASE (NAME, PRICE) VALUES ('Средняя', 2.5);
INSERT INTO PUBLIC.BASE (NAME, PRICE) VALUES ('Маленькая', 2.5);
INSERT INTO PUBLIC.BASE (NAME, PRICE) VALUES ('Тонкая', 2.5);
INSERT INTO PUBLIC.BASE (NAME, PRICE) VALUES ('Ультратонкая', 2.5);
INSERT INTO PUBLIC.BASE (NAME, PRICE) VALUES ('Пита', 1.5);

