INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Italian pizza', 'Florentino', 0, null, 2);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Dangerous pizza', 'Columbia', 0, null, 2);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Italian pizza', 'Florentino', 0, null, 2);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Italian pizza', 'Celimesto', 0, null, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Dangerous pizza', 'Muchacha', 0, null, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Italian pizza', 'Majorino', 0, null, 1);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Italian pizza', 'Churesco', 0, null, 2);



INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Italian pizza', 'Marrreza', 0, null, 2);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Dangerous pizza', 'Zoretta', 0, null, 2);
INSERT INTO PUBLIC.PRODUCT (DESCRIPTION, NAME, PRICE, BASE_ID, CATEGORY_ID) VALUES ('Italian pizza', 'Voljano', 0, null, 2);