INSERT INTO PUBLIC.INGREDIENT (NAME, PRICE, TYPE) VALUES ('Mozarella', 1.5, 'CHEESE');
INSERT INTO PUBLIC.INGREDIENT (NAME, PRICE, TYPE) VALUES ('Pork', 3.5, 'MEAT');
INSERT INTO PUBLIC.INGREDIENT (NAME, PRICE, TYPE) VALUES ('Beef', 4, 'MEAT');
INSERT INTO PUBLIC.INGREDIENT (NAME, PRICE, TYPE) VALUES ('Tomato', 1.5, 'VEGETABLE');
INSERT INTO PUBLIC.INGREDIENT (NAME, PRICE, TYPE) VALUES ('Onion', 1, 'VEGETABLE');
INSERT INTO PUBLIC.INGREDIENT (NAME, PRICE, TYPE) VALUES ('Cheddar', 2,'CHEESE');