INSERT INTO PUBLIC.ORDER_ITEM (DESCRIPTION, PRICE, ORDER_ID, PRODUCT_ID) VALUES ('Onion', 0, 1, 1);
INSERT INTO PUBLIC.ORDER_ITEM (DESCRIPTION, PRICE, ORDER_ID, PRODUCT_ID) VALUES ('Spice', 10, 1, 1);
INSERT INTO PUBLIC.ORDER_ITEM (DESCRIPTION, PRICE, ORDER_ID, PRODUCT_ID) VALUES ('Cucumbers', 25, 1, 1);