INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER) VALUES ('Большая', 2.0);
INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER) VALUES ('Средняя', 1.5);
INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER) VALUES ('Маленькая', 1.0);
INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER) VALUES ('Тонкая средняя', 1.2);
INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER) VALUES ('Тонкая большая', 1.8);
INSERT INTO PUBLIC.BASE (NAME, PRICE_MULTIPLIER) VALUES ('Кальцоне', 1.5);

